### ISSUE TITLE
[Bug]: No package matching 'gnupg' is available

### ISSUE THREAD

**Issue by JonasPammer** [JonasPammer/ansible-role-bootstrap#37]
### What happened?

https://github.com/JonasPammer/ansible-role-core_dependencies/runs/5694366210

The role itself should pre-heat the the package manager cache.
Maybe not every-time, but at least when the failure as seen in above workflow run happens.
This is currently only being done when the connection failed, e.g.: https://github.com/JonasPammer/ansible-role-bootstrap/blob/7f948c260e5cb0506e098839c0dc7e53c97535e2/vars/main.yml#L33

This has also been reported a long time ago in robertdebock's original role, but with a stagnating pull request: https://github.com/robertdebock/ansible-role-bootstrap/pull/57

### Playbook

```yaml
---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: jonaspammer.bootstrap
```

### Role Version

1.0.0

### Environment / Control Node Information

```shell
debian 10
debian 11

ansible 2.9, 2.10, 2.11, 2.12
```

### Environment / Managed Node Information

```shell
github's ubuntu-latest
```
